### ISSUE TITLE
outsideClickIgnoreClass is not compatible with CSS Modules. Suggesting to pass refs instead of class names

### ISSUE THREAD

**Issue by seleckis** [Pomax/react-onclickoutside#134]
I use CSS Modules, so if there is an element, which I need to ignore is outside the container, it is not possible to define class name here. I think that better and surely react-way would be passing **ref** to react-onclickoutside HOC, but not class name. Something like this:

```js
…
render() {
  return (
    <Drawer outsideClickIgnoreRefs={[this.refs.ignoreMe]} />
    <div ref="ignoreMe"></div>
  );
}
…
```
for now `this.ignoreMe` will return undefined, but I can save and pass it as state.

**Comment by Pomax** [comment]
What are CSS modules?

**Comment by seleckis** [comment]
https://github.com/gajus/react-css-modules

**Comment by Pomax** [comment]
I don't quite understand why that would get in the way of also assigning additional custom classes. Does CSS Modules destructively ignore `className` props? If so that is a thing that it should probably fix...

**Comment by seleckis** [comment]
Oh, I've forgot about className attribute, CSS Modules uses styleName. :)

**Comment by Pomax** [comment]
An odd choice of name (since HTML elements have both `class` and `style` attributes, with classes having names, whereas styles don't) but good to know that it's not interfering with the React `className` (which they had to use because `class` is a reserved JS keyword property for elements =)

**Comment by seleckis** [comment]
I see, but it would be better, if you could find solution with refs, to be not rely on class attribute, because class is commonly used for presentation, not for elements identification.

**Comment by Pomax** [comment]
you *can't use refs* because refs don't exist for stateless components. They're not universal.

**Comment by seleckis** [comment]
No, i mean, to add some statefull wrapper for that? Check out the Note here https://facebook.github.io/react/docs/reusable-components.html

**Comment by Pomax** [comment]
The ignore class is resolved on the DOM of the *wrapped component*, so it needs to resolve on an HTML element (because we have no guarantee that the content is 1) a React component and 2) a stateful React component). That means we have to use HTML attributes, which are basically `id`, `class`, `style`, and that's it, there aren't all that many more global attributes that are guaranteed to work on all elements in the HTML5 bag.

Obviously `id` and `style` are out, they do not take arbitrary string data, but `class` is exactly what we need to use here: it is an arbitrary listing of functional classes an element should express. While due to historical baggage it's easy to claim that it's for CSS classes, that is *not* what what it's for:

> Every HTML element may have a class attribute specified.
> 
> The attribute, if specified, must have a value that is a set of space-separated tokens representing the various classes that the element belongs to.
> 
> NOTE: Assigning classes to an element affects class matching in selectors in CSS, the getElementsByClassName() method in the DOM, and other such features. 
>
> -- http://w3c.github.io/html/dom.html#classes

Classes are just generic classes, and if you use the same name as a CSS class then browsers interpret that as CSS class application, but that is *not* "what classes are for", they are for imparting arbitrary semantics to an element beyond its normal HTML role, for use with your own page logic. They are *explicitly intended* for things like what this HOC uses it for.

**Comment by seleckis** [comment]
Thank you for detailed answer, but I know that. That is why i said "because class is **commonly** used for presentation" (and used by developers, not by w3c)

Ok, I'll try to find a solution, and inform your about the result.

**Comment by Pomax** [comment]
thanks
