### ISSUE TITLE
Regulating evt.preventDefault() & evt.stopPropagation()

### ISSUE THREAD

**Issue by t1mmen** [Pomax/react-onclickoutside#145]
Hi,

First off, thanks for this lib, it's been very helpful!

Secondly, I'm running into a few situations where working around the current `preventDefault` & `stopPropagation` limitations are a big pain in the ass. Do you have any plans for implementing them in the way they usually work?

```jsx
// for example..
handleClickOutside(event) {
    event.stopPropagation();
   // .. etc
}
```

I looked over the source if I could make sense of it, but this is a little more low-level than I'm used to. If you have ideas for how this could be done, I'd be happy to take a stab with some guidance :)

**Comment by Pomax** [comment]
Does https://github.com/Pomax/react-onclickoutside#regulating-evtpreventdefault-and-evtstoppropagation not do what you need, here?

**Comment by t1mmen** [comment]
@Pomax Thanks for the response!

As I understand it, those are `props` that need to be passed in to whatever component I'm using `onclickoutside` on, correct?

In the majority of my use-cases, the parent component doesn't know if it's child component should `stopPropagation`/`preventDefault` or not. I _could_ communicate from child to parent, `setState`, and pass that as `props`, but that'll end up as a lot of added complexity to solve a problem the native web already has an elegant solution to?

I've been thinking that I could revert back to using the `mixin` via my own wrapper component, as I believe that supported the `someFunc(event) { event.stopPropagation(); }` way of doing things.

**Comment by Pomax** [comment]
Why would your parent component not know? *You* are the designer of your code, so you know whether a component is going to have to need to listen to outside clicks. That means you know whether clicks should propagate or even prevent default browser behaviour at the same time?

Can you explain your usecase where you have a situation that you have a component that needs to listen to outside clicks, but where you *don't know* what should happen to the event chain?

**Comment by t1mmen** [comment]
Ah, ok, I see how my request could be confusing. I'll attempt to explain:

At Timely, we're using a popout interface for changing time tracking entries:

![screenshot 2016-11-15 14 03 45](https://cloud.githubusercontent.com/assets/192263/20326431/a0a7ed4e-ab3d-11e6-9ad3-9068dcd2091a.png)

When clicking outside of these popouts, the popup should close (which triggers a save), with a few exceptions:
- There are validation errors that we catch client-side.
- The user has typed in an project name that doesn't exist (which triggers another popover to create a new project).

In the first case, I might not know of validation errors until the user attempts to close the popover (ie, focus is on "notes" entry that, onBlur, does some validation)

In the second case, I'd like click-outside to only close the "new project" popover, NOT the "edit time entry" popover.

Does that make sense?

**Comment by Pomax** [comment]
Ah, I see. One thing you can do right now is to give these additional popovers a class like `no-on-click-outside-please` and then pass this into the component that gets onclickoutside-wrapped, so that https://github.com/Pomax/react-onclickoutside#marking-elements-as-skip-over-this-one-during-the-event-loop kicks in.

As for the validation error I suppose that depends on how they're handled - if the dialog stays open then the user won't be clicking outside of it, I'd imagine (or if they do, that's an intentional act on their part?) so I'm not 100% sure where that benefits from additional preventDfault/stopPropagation handling.

**Comment by t1mmen** [comment]
I'll attempt the `ignore-react-onclickoutside` workaround once again tomorrow, thank you. I did try this before, but I might've gone about it wrong. I see the value of the class blocking events, I just find it a little confusing to keep track of classNames in different components, compared to regular event handling I guess.

As for the validation thing: yeah, the intended action is to close & save changes, but the validation failing should block that intent, as the ultimate goal is to get their hours logged correctly.

In any case, thank you very much for taking the time to respond! If you're ever in Kelowna, B.C, please let me know and I'll buy you a beer or five :)

**Comment by Pomax** [comment]
Yeah, the idea behind the class is that ideally you don't have to think about what to call it, it's just one very specific classname and it "should just work(tm)".

As for the validation: I don't quite understand where the closing happens. Do you mean that there is no "save" or "apply" button or something, but your user fills in the data, then clicks outside the dialog to commit that? If so that's an interesting and concrete case for adding a function as part of the wrapping options object that returns true or false, to determine whether the outside click should be honoured or not.

I'm in Burnaby, lived in Vancouver since 2011, but *still* haven't been up to Kelowna. It's kind of shameful really, but there are thoughts of a BC roadtrip bubbling =)

**Comment by Pomax** [comment]
closing for now, but feel free to reopen or refile if this becomes a problem again.

**Comment by Dante-101** [comment]
First, thanks for the package! It's awesome! :)

I am having a bit of trouble around preventDefault in chrome. When I pass preventDefault=true as prop, I get this warning in the chrome and preventDefault fails.
index.js:68 Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

It works fine in Firefox.

**Comment by Pomax** [comment]
Interesting... do you have a stack trace, and maybe STR? (and is this a mouse or a touch event?)

**Comment by Dante-101** [comment]
I did it with a mouse event. I don't have a stacktrace but this error is occurring on all Chrome   versions after 54.

**Comment by Pomax** [comment]
Can I ask you to file a new issue?

**Comment by Dante-101** [comment]
Done. Here it is.

https://github.com/Pomax/react-onclickoutside/issues/168
