### ISSUE TITLE
Cannot click iframe

### ISSUE THREAD

**Issue by bpatterson-r7** [Pomax/react-onclickoutside#152]
I have an iframe in my app and react-onclickoutside doesn't detect when I click inside it. I have a feeling that its because the iframe has a separate dom so its not considering that as a part of the rest of the dom.

**Comment by Pomax** [comment]
That would be how the web works. Parents are not informed about what happens inside an iframe because that would insecure as hell. You'd be able to listen to a user typing their banking password etc. If the iframe needs to be "part of the page" the first course of action is of course "stop using an iframe at all" but the second option is to make the iframe use `postMessage` to communicate events to the parent, so that the parent can then create synthetic events for its own event listeners to pick up on.
