### ISSUE TITLE
React components can return null, "Return null" warning not necessary

### ISSUE THREAD

**Issue by mrscobbler** [Pomax/react-onclickoutside#161]
The warning that pops up when a component returns a `null` value is not necessary.

See here:  
https://facebook.github.io/react/docs/conditional-rendering.html#preventing-component-from-rendering

**Comment by Pomax** [comment]
It's incredibly necessary for this particular library, because a component that renders `null` has no DOM node associated with it. Instead, if you have two components X and onClickOutside(Y), then Y should never render as `null`, and instead X is responsible for determining whether or not to render Y at all -- so rather than setting a property on Y that lets it figure out whether or not to draw it, X is now responsible for simply not even rendering Y, rather than rendering it with `someprop={someValueThatWouldHideIt}`.

**Comment by mrscobbler** [comment]
If there is no DOM node, why not disable the onClickOutside functionality?

**Comment by mrscobbler** [comment]
On another note, I really appreciate the error messages in the console! It was very detailed and helpful. :)

**Comment by Pomax** [comment]
That's a reasonable idea for when you're only dealing with X rendering Y, but typically in this situation you end up a large number of elements, where disabling the functionality isn't an option because menu itself and *some* of the options are still hanging around.

So in this case it's better to make sure the code has the right separation of concerns (and responsibility). While code-technically you can of course have a `render()` return null, design wise your life's going to be a lot easier if the parent decides whether to even show particular children at all. Hence the warning (and it seemed unreasonable to make it a true error, so you *can* still use the library, but it might not behave quite as you might expect due to the difficulty of having to deal with "gaps" in the DOM)

**Comment by gaearon** [comment]
Is it possible to check if DOM node exists in `componentDidUpdate` (in addition to your code in `componentDidMount`) and tear down or set up the listeners accordingly? Then you won't need to tell users not to return `null`. React will call `componentDidUpdate` after every DOM flush so this should give you enough information.

**Comment by Pomax** [comment]
It might very well be, marking as help wanted.
