### ISSUE TITLE
Excessive warning in production

### ISSUE THREAD

**Issue by Andarist** [Pomax/react-onclickoutside#162]
It mainly is about [this part of the code](https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L155-L168). Ideally we should restrict such wall of text only to dev mode.

However the lib is now a one file without any build tool dependency (although [`webpack` is listed as one](https://github.com/Pomax/react-onclickoutside/blob/11041bea568734673d3f7f49a9d9a1dd0fc0a796/package.json#L51)). Shouldnt one be incorporated so such part of the code could be envified?

**Comment by Pomax** [comment]
Why? It's a single file that doesn't need a build. I don't agree that this wall of text should only be in dev mode: if your code isn't compatible with a library, then pushing that out to production is a little iffy. Right now, the library *cannot* deal with the pattern you're getting warnings for reliably so there's a few options:

-  Change the pattern you use in your code (this might be a completely unreasonable or even intractable thing to do of course)
- See whether you can file a PR against this library that makes it work with the pattern you clearly rely on (might be a more bit initial work, but the payoff is that the warning goes away for _everyone_, not just you)
- use a different library (which depending on the needs might also be unreasonable)

If you're interested in taking a stab at outright fixing it, there is a prior discussion in https://github.com/Pomax/react-onclickoutside/issues/161 on what the probably cause is and how it can be fixed, so that the warning that is currently necessary because the library is *in no way guaranteed to work* when you see it. And that makes it rather important to keep showing. 

I might try to tackle this eventually but my plate's pretty full so if this is something you need fixed sooner than later, pop over to the other issue and see if that is worth your time. If it is, I'll be more than happy to review and merge in a reasonable PR,

**Comment by rafeememon** [comment]
@pomax, I think it's important to note that developers that _are_ using this library correctly still must incur the overhead of shipping the ~1KB "wall of text" in their bundles with no automated way to remove it.  Generally the convention is to wrap the block in a `process.env.NODE_ENV !== 'production'` check that can be minified away.  See:

* This similar example in the react codebase: https://github.com/facebook/react/blob/v15.4.2/src/shared/utils/flattenChildren.js#L21
* Recommendations re: performance when building react itself: https://github.com/facebook/react/blob/v15.4.2/docs/docs/optimizing-performance.md

**Comment by Pomax** [comment]
Yes, and that solves the symptom, not the problem. So: instead of PRs that introduce a NODE_ENV check, it will be by far a much better strategy for everyone using this library (literally) to instead fix the reason why the library has to throw that warning at you.

**Comment by Pomax** [comment]
Awesome, I'll be happy to comment on any questions in the code you might diving into the underlying problem.

I fully agree that the wall of text is undesired, which is literally the reason I'm keeping it in, instead. Think of it as an open source motivator: this library is wildly popular, and makes a difference to people in literally monetary ways. The library also has a (glaring?) flaw at the moment that needs some help to get fixed, and hiding a warning instead means people have a way to completely ignore the problem instead of helping to get it fixed because the hack around it is "good enough" and there will be no impetus for anyone to help fix the real problem.

**Comment by Andarist** [comment]
Fixed in https://github.com/Pomax/react-onclickoutside/pull/170
