### ISSUE TITLE
Ref issue - interoperability with layers of HoCs

### ISSUE THREAD

**Issue by Andarist** [Pomax/react-onclickoutside#163]
Aint sure if there is any established pattern how to do this.

Use case: accessing `wrappedComponent`'s ref in each HoC wrapping it. 

More [here](https://github.com/yannickcr/eslint-plugin-react/issues/678#issuecomment-291816217)

Happy to send a PR if we can figure out how this should be tackled on library level.

**Comment by Pomax** [comment]
This is really something to discuss on the facebook react issue tracker instead - It would be amazing if someone could formally declare that any HOC should offer two functions that return the class definition and the wrapped instance, so that all (or at least all the currently popular) HOC can be updated accordingly.

This one uses `.getClass()` and `.getInstance()` for that purpose (see https://github.com/Pomax/react-onclickoutside#but-how-can-i-access-my-component-it-has-an-api-that-i-rely-on) but if the React team can formally declare that one set of function names is to be the preferred method of guaranteeing HOC chaining works without effort, I will immediately update them to reflect that.

**Comment by Pomax** [comment]
As quick followup, `refs` rebinding is probably not good enough, as there is no rule that says you can only ever pass a single component into a HOC, and no rule that says HOCs may only use refs for contained components, so in order to make sure you can access "all" passed components you would need to do a blanket `refs` rebinding, but that will also expose references for bits that are internal to the HOC itself and should not be accessible for fiddling with.

**Comment by Andarist** [comment]
Yes, probably I'll write something up, just need to gather thoughts up.

**Comment by Pomax** [comment]
I've been thinking about this for a while myself, too, so I figured I might as well file https://github.com/facebook/react/issues/9345 to get the ball rolling.

**Comment by Pomax** [comment]
I'm going to close this issue because this is not a thing we can solve "for everyone", and it's not an issue Facebook cared to solve with an authoritative API (as per the linked issue on their tracker)
