### ISSUE TITLE
Unable to preventDefault on Chrome

### ISSUE THREAD

**Issue by Dante-101** [Pomax/react-onclickoutside#168]
I am having a bit of trouble with preventDefault in chrome. When I pass `preventDefault={true}` as prop, I get this warning in the chrome and preventDefault fails.

> index.js:68 Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

I also fails with the same error when I try `event.preventDefault()` inside `handleClickOutside(event)`

The error occurs on all Chrome versions >=54. It works fine on Firefox.

**Comment by Pomax** [comment]
Can you add some more details on the events you're using? Would you be able to reduce this to a demonstrator component that can reproduce this behaviour?

**Comment by Andarist** [comment]
The whole point of `passive` event listener is to assure the browser that you wont call `event.preventDefault()`. However this library is not using a passive listener, are you sure the error is coming out of the library's code? Maybe you are testing on some mobile device? (they tend to differ in some default behaviours)

**Comment by Dante-101** [comment]
Sorry for the late reply. I will post a sample code soon.
As the chrome status mentions, 
>  With this change touchstart and touchmove listeners added to the document will default to passive:true (so that calls to preventDefault will be ignored)
This problem occurs on mobile versions of Chrome. You can replicate it on desktop Chrome browser by toggling it to mobile version from developer tools.

**Comment by Andarist** [comment]
@Dante-101 ive created a PR which should fix the issue (I think)

**Comment by Dante-101** [comment]
I believe we also need to handle this case.
```
handleClickOutside: function(evt) {
evt.preventDefault()
}
```

**Comment by Andarist** [comment]
what do u mean? could u point to the exact place in the source code?

**Comment by Dante-101** [comment]
Let's mention it in the documentation early on?

My first instinct after seeing the function `handleClickOutside(event)` was to do `event.preventDefault()` inside it because that is the most common/expected way of doing it.
I dug deeper when it didn't work and found prop.preventDefault.

Ensuring that the api works with expected way of programming goes a long way in ensuring developer friendliness.

**Comment by Andarist** [comment]
Hm, maybe also a `passive` prop should be accepted to make this more explicit. Wont ofc make this more obvious at first, but if somebody meets the problem it will be better documented for them too seek out for the solution.

Wouldnt be really feasible to handle `event.preventDefault()` calls from inside the `handleClickOutside` without proxying `event` and I think its not really worth a hustle.

cc @Pomax

**Comment by Pomax** [comment]
@Dante-101 this is documented already in https://github.com/Pomax/react-onclickoutside#regulating-evtpreventdefault-and-evtstoppropagation Given the number of sections on all the things you can configure, moving any of them "up" also pushes all the rest "down", when all of them are important, and you kind of need to read the entire README.md once before you start to use this hoc (or any library, really. Already read the docs at least once).

A discussion about `passive` events is in https://github.com/Pomax/react-onclickoutside/pull/166 but the gist is that there is nothing this hoc should be doing that requires passive events. If you are seeing errors about passive events because you've set `preventDefault={true}` on your component, then that is something we need to look at (but then probably in a new issue specifically around the fact that `preventDefault` is not doing what it should reasonably be doing)

**Comment by Dante-101** [comment]
Fair enough.  Do you think the documentation should mention to not fiddle with the events?

There are errors on mobile Chrome with `preventDefault={true}`. It works for all other cases.

**Comment by Pomax** [comment]
to be honest, that's kind of assumed. You typically don't try to do a library's job for it, so if the library docs say there are provisions for preventDefault of stopPropagation, you just let it take care of that.

Can you please create a jsbin.com example that I can load in Chrome 58 on Android 6/7, with just enough code to show that thing go wrong with `preventDefault={true}` set?

**Comment by Andarist** [comment]
https://codesandbox.io/s/vggXow1v5

**Comment by MrJadaml** [comment]
> If you are seeing errors about passive events because you've set preventDefault={true} on your component, then that is something we need to look at (but then probably in a new issue specifically around the fact that preventDefault

I am having issue with `preventDefault` not working on mobile chrome as well (works just fine outside of mobile). Was the issue related to passive events ever fully sorted out as mentioned above?

**Comment by Andarist** [comment]
Yes, it should be resolved with the latest version. Could u share reproduced issue?

**Comment by MrJadaml** [comment]
https://codesandbox.io/s/jzk68135yw

Here is a simplified version of what I am doing. In my case I have a grid of images where the blue container is. In Chrome's mobile device mode when you click outside of the panel to close it, it opens up the image where the click registered. When not in Chrome's mobile device mode it works as expected not registering the click.

In the sample provided you can see that in mobile device mode you get a warning letting you know it was not able to _preventDefault_

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

**Comment by Andarist** [comment]
@MrJadaml it seems that you use an outdated version of the `react-onclickoutside`. Please upgrade, it got fixed.

**Comment by MrJadaml** [comment]
ah, looks like codesandbox just loaded an old version by default. Anyhow, I updated the version in the sample to 6.4 and it still produces the same Intervention warning. Also the version in my application is also 6.4 and has the same warning.

**Comment by Andarist** [comment]
@MrJadaml thanks for the reproduced case, it was really helpful in fixing this. Could u try to
```sh
npm install react-onclickoutside@next
```
and try this out? Im pretty confident it will help your case (checked on the codesandbox), but your confirmation would be great before publishing this as `latest`.

**Comment by MrJadaml** [comment]
@Andarist That did the trick! Thank you!

**Comment by Andarist** [comment]
@MrJadaml thanks for the confirmation, I'll probably release it for others in the future week.

**Comment by leomyth330** [comment]
This problem happens on mobile versions of Chrome. Was it fixed?

**Comment by BlackKhm** [comment]
Now it still happen on chrome device android.

**Comment by Pomax** [comment]
React has had hooks for quite a while now, you probably want to switch to those instead, in which case there's very little sense in still using this HoC because a few lines of code will do the same thing without needing an entire dependency.

See https://github.com/Pomax/react-onclickoutside/#functional-component-with-usestate-hook for more details.
