### ISSUE TITLE
Deprecate Mixins?

### ISSUE THREAD

**Issue by dmatteo** [Pomax/react-onclickoutside#18]
Hey there,
I need this behaviour in several part of our app but I don't want to drag in a dependency on mixins, since they're not gonna be supported anymore.

I was about to write another component to handle that in  a declarative fashion, but maybe you would like to have a PR here and move away from mixins?

**Comment by Pomax** [comment]
Not "wanting to drag in a dependency on mixins" seems the wrong way to think about code that inherently relies on `require` calls, but more importantly I don't see any notice about deprecation of mixins anywhere in the React docs, or blog. Got a link to back up that statement?

**Comment by dmatteo** [comment]
Exactly because of ES6 classes
https://facebook.github.io/react/docs/reusable-components.html#no-mixins

I don't think it's ok to rely on babel to make use of "deprecated" features. 

The trend in the community is to move away from mixins, and https://github.com/rackt/react-router it's probably one of the biggest examples.

Why would you want to stick with mixins?

**Comment by Pomax** [comment]
I don't think you're using that word correctly. Mixins are part of React, and not deprecated. Native ES6 classes (which are not the same as React's classes), howeer, do not currently support mixins so you can't switch over to true native ES6 right now without losing features. Nothing new there, that's been the case since React was released. So: that's your choice. If you want to use native ES6, you lose some features that may be important to you (or should be, depending on your architecture), so you might not be able to switch right now. That doesn't mean mixins are deprecated, it just means React is not 100% ES6 compatible at the moment. So that's status quo: it's never been, but it's getting closer and closer. The React team's looking at how to get mixins working within the ES6 classes concept, and when they do, hurray, we can stop using babel-loader. Until then, not so much.

You perhaps don't understand why mixins exist: they're for blocks of code that impart universal behaviour to components based on functionaly that triggers during lifecycle hooks. The community is not moving away from those, although the way that functionality is achieved may in the future change so that it's ES6/7/8 compatible. At which time I'll switch this code over, but not before then.

Also React-Router is really not really a good example: it's a complex component implementation that never even made sense to try to write as a mixin, so they never did. A better example would be something like the `react-draggable` component, because that can be implemented as either/or. The author of that went with the component implementation, so you could try to raise that as evidence but most components like these mean you end up wrapping your real content in deeply nested "purely to achieve fuctionality" JSX tags, which is horrible to read and semantically meaningless, so if you've read any of my posts you'll know why I will say that's ridiculous and those things should have been mixins.

(relevant posts here would be http://pomax.github.io/1419289380022/so-you-re-thinking-about-using-react, http://pomax.github.io/1420592591221/taking-react-to-the-next-level-mixins-gulp-and-browserify and http://pomax.github.io/1433888478288/whose-state-is-it-anyway-further-thoughts-about-react)

**Comment by dmatteo** [comment]
I didn't use "deprecated" as in *deprecated*, which is why I used quotation marks, but nevertheless, I was wrong apparently.

Luckily I know the difference between ES6 classes and React.createClass, and I know what mixins are for, but I apparently misunderstood the "mixins are going away" sentiment, as the react-router guys says in the [upgrade guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md). Apologies for that.

Mixins are not going away anytime soon, but they are not going to implemented in future React as they are now either. The most likely candidate seems to be ES7 decorators, but we'll see.

I don't share your sentiment about the universal ugliness of wrapper components, but I guess that's my point of view there.

See you around and thanks for your time.

Cheers

**Comment by Pomax** [comment]
ES7 decorators would be interesting, as a way to add in the parsing of the `mixins` array if you need it, moving some of the more complex functionality out into their own decorators.

My beef with components is twofold, really. In part it's the fact that it turns into the kind of code that is *super bad* for contributors to work on, like:
```
<Draggable>
  <VisibilityChecked>
    <ColorCorrection>
      <ImageLoader src="..."/>
    </ColorCorrection>
  </VisibilityChecked>
</Draggable>
```

(in the plain JS notation this is even worse; it becomes  a massive block of "nesting hell")

The other part is related to what React is supposed to be for: writing easy to read, easy to maintain UI code, with JSX syntax for easy to read, easy to write components, and using plain JS for tacked on functionality.

The idea of then writing functionality libraries *as* components violates that concept, because `Draggable` and `VisibilityChecker` and `ColorCorrection` don't impart UI, they are purely there to achieve some programmatic functionality. So the letter of the law is obeyed ("the code works, and it uses zero hacks, it's all plain React"), the spirit of the law gets completely ignored. While natural given that you always bring experience with you when you move to something new, React is different enough to go "those things do work, yes, but that's not reading up on React, and seeing how it's supposed to work *and why*, and then following that spirit".

**Comment by dmatteo** [comment]
I can see your point against components as a mean to add functionalities, and I agree with you that when is overdone (or over-engineered, for that matter), than it become a problem.

On the other hand, I like very much the declarative essence of it, which makes immediately crystal clear what is going to happen there.

A non existent example could be:
```javascript
<OnClickOutside clickOutsideDelegate={foo}>
  <SomeOtherComponent />
</OnClickOutside>
```
vs.
```javascript
  <SomeOtherComponent onClickOutside={foo}/>
```
or even worst, without any delegate, which makes it impossible from the outside to know beforehand that some magic is happening inside there.  
The most common problem is, as usual, debugging someone else code, where you don't really know immediately what's going on.

Do you still prefer the "mixin approach" regarding code clarity and readability?

**Comment by Pomax** [comment]
I'd have to say so: those examples are equally informative to me; the difference is mostly cosmetic for debugging: "things are wrong, what's my wrapper stack" vs "things are wrong, what's my mixin stack". Mixins without handlers might seem "trickier" on paper, but using reasonable debug tools (say, Chrome + the React debug tools) I haven't run into a situation where I got stuck on anyone's code yet. Plus ideally, you've written tests for your own code so you can tell if something you're seeing is your fault, or whether you need to start code diving. For small projects you don't, but then for small projects the debug tool chains available are quite good.

**Comment by HeyHugo** [comment]
Hi,

have you read this [blog post] (https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)?

I think that way of composing components  would be nice. Then the API for this package could look something like this:

With experimental ES7 decorator feature:
```
 @clickOutside
 class ExampleComponent extends React.Component {
   ...
```

otherwise:
```
class ExampleComponent extends React.Component {
  ...
}

ExampleComponent = clickOutside(ExampleComponent);
```
