### ISSUE TITLE
add useCapture prop

### ISSUE THREAD

**Issue by primetwig** [Pomax/react-onclickoutside#220]
Hi,
Thank you for your great work!

Could you be kind enough to add support of passing `capture` prop to `addEventListener` and `removeEventListener` respectively?
You can name prop as `useCapture` (as it is used in documentation).

You have a line in readme:
> the coded uses stopPropagation={true} but sibling events still make it to "parents".

This change will fix it 😉

**Comment by Pomax** [comment]
Thanks for the ePR, but I'm going to have to decline it for programming reasons: this would solve the problem *only* f this was the only `usecapture` issued, but the moment you have two or more (says some other event also generates with usecapture=true) then there is --as per the spec-- zero guarantee on which one gets to go first, and so you end up back in the same situation as before.

That's why I haven't added it: without `usecapture`, you *know* sibling events will always still happen and you will have to make sure your code knows how to deal with that fact: it is 100% predictable and reliable behaviour. However, with `usecapture,` you *think* they won't run into this situation, but you actually *might*, and now you have a near-untracable source of bugs due to non-deterministic browser behaviour.

Having deterministic code behaviour is far more important here =)

**Comment by primetwig** [comment]
Yes, I know. That`s why I ask you to make this property optional (having `false` by default).
I use another third-party library for some clickable elements on the page, that do not provide enough way to handle their events. So I look for a way of preventing them from outside.
It is not a breaking change but an opportunity to make your component more flexible.
Thank you.

**Comment by Pomax** [comment]
It sounds like you're trying to use `useCapture` to solve a problem that it was not designed to solve.  Order of execution is 100% not guaranteed so using `useCapture` is literally a bug if you *think* you're using it to add some kind of order of execution. If you really that kind of event examination, then write an event handler that you can pass to two or more components, and have the logic that determines "which gets to go through" live inside that function.

**Comment by jfpalacios** [comment]
what spec is this exactly? based on this 

https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener
>  First all object’s ancestor event listeners whose capture variable is set to true are invoked, in tree order. Second, object’s own event listeners are invoked. And finally, and only if event’s bubbles attribute value is true, object’s ancestor event listeners are invoked again, but now in reverse tree order.

it shows they are invoked in tree order. For my case I would like to block an onClick event completely before it reaches the bubble phase in certain scenarios. Even if the capture events weren't in a determined order, it seems that they will all finish before the bubbling phase, no?
