### ISSUE TITLE
Question: stop propagation when clicking outside?

### ISSUE THREAD

**Issue by stevewillard** [Pomax/react-onclickoutside#35]
Is there any way to to stop the event from bubbling when clicking outside? I tried something like
```
handleClickOutside: function(event) {
    event.stopPropagation()
}
```

I also tried the nativeEvent and other variations of this. It still seems to be triggering other onClick events, for example.

**Comment by Pomax** [comment]
stopPropagation isn't part of the React event, is it? Try `event.nativeEvent.stopPropagation()` and see if that works.

**Comment by stevewillard** [comment]
Tried that too, no dice :( Actually there might be a bug here... when I do:
```
  handleClickOutside: function(event) {
    event.nativeEvent.stopPropagation()
    this.setState({ showAssignDropdown: false })
}
```

```
Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
```

**Comment by Pomax** [comment]
Hmm. good point, I'm using a base event, not native!

The odd thing is this: https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L60 where the event is already getting explicitly not-propagated... What are you seeing it do? (it doesn't preventDefault, so that could be another thing you're seeing)

**Comment by stevewillard** [comment]
Ah I just installed from master. I guess NPM doesn't have the latest changes? I was missing the stopPropagation()

Unfortunately that doesn't seem to help me. What I really need is stopImmediatePropagation() (https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) instead of stopPropagation(). I want to prevent other handles from firing, not just parent handlers.

I would be happy to update stopPropagation to stopImmediatePropagation, if you think that's a reasonable change. It would definitely help me out!

**Comment by Pomax** [comment]
oh weird! Let me push up the latest version O_o

**Comment by Pomax** [comment]
v0.3.2 published to npm

**Comment by Pomax** [comment]
If you want to add a stopImmediatePropagation call in the form of a PR, I'll happily merge it in.

**Comment by Pomax** [comment]
v0.3.3 published

**Comment by kpaxqin** [comment]
@Pomax I don't think it's a reasonable change, the stopImmediatePropagation will block all remaining listeners ! 
Just think we got two components(like datepicker) with react-onclickoutside on our page , the second one will **never** work properly because of the stopImmediatePropagation call in the first one's listener. 
And this is the problem I meet now.

If you really want stopImmediatePropagation in some situations, maybe call it in the `handleClickOutside` is a better choice.

**Comment by Pomax** [comment]
reverted.
