### ISSUE TITLE
global is not defined.

### ISSUE THREAD

**Issue by jonchay** [Pomax/react-onclickoutside#51]
I'm installing this mixin through the browser method where `root` is the window. But in the function itself I receive an error on the console that states `global is not defined.`. 

I added `global = this;` in the function and it fixes it. Is this the right approach?

**Comment by Pomax** [comment]
yeah it looks like the `global` var got unbound, which needs fixing. a temporary binding works, but really this needs a fix in the mixin itself

**Comment by Pomax** [comment]
fix pushed as 4.2.0

**Comment by nathanbrock** [comment]
Hi @Pomax. Firstly, big thanks for the react-onclickoutside lib and the work you've put into it.

I'm currently working with the react-datepicker module and started experiencing issues this afternoon after updating modules via npm.

The problem seems to be caused by the variable being changed from global to root, as per this issue.

The error being thrown is 'Reference error: root is not defined'. I've probably missed something but the only 'root' variable is defined in the first module loader function parameter, which the 'enableOnClickOutside' method doesn't seem to be able to access within its scope.

Are you or anyone else experience similar issues? 

Many thanks,

Nathan

**Comment by roderickhsiao** [comment]
I got the same root is not defined error on our project as well.

**Comment by Pomax** [comment]
naturally, `root` was not actually passed into the function =_=  Fixed that in 4.3, thanks for letting me know

**Comment by uniphil** [comment]
ran into that one as well, thanks for the quick turaround @Pomax !!
