### ISSUE TITLE
Internet Explorer 9 isSourceFound error

### ISSUE THREAD

**Issue by laxplaer** [Pomax/react-onclickoutside#60]
Unable to get value of the property 'contains': object is null or undefined

```
source.classList.contains(IGNORE_CLASS)
```

**Comment by Pomax** [comment]
Before we address that, why are you using IE9? And this is a serious question, because if you're on a system that can even *run* IE9 (Windows Vista and later), then you are on a system that can run IE11, and should upgrade.

17 days from now, Microsoft is officially ending support *of any kind* for IE9 on modern Windows, so patching this in order to make it run on a browser that is literally about to be abandoned seems like the wrong solution to the problem of IE9 not supporting something. Use a browser that isn't 2 months short of being five years old.

**Comment by laxplaer** [comment]
You do not have to explain this to me.. :) Since we have signed a stupid contract and bind ourself to actually support IE9 I do not have much other options.. Personally I am using IE9 only for testing purposes in Windows 7 virtual.. And still if you check some stats a lot of browser usage, IE9 have still a high number.. I am aware of ending support, but still regular users will be using this old fashion browsers.. It would be at least nice to prevent throw an error if there is no other options..

**Comment by Pomax** [comment]
IE9's number is pretty low these days. It's around 2% and declining, and after January 12th when microsoft shuts it down hard, that number's going to drop off even more. If you absolutely need to support IE9, use a shim that adds classList support. There are at least [two options](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#classlist).

**Comment by vizath** [comment]
FYI, it is happening to our clients in IE11.
We do not have a test case though. We received the error in Bugsnag.
Windows 7.1, 8 and 10. With 6 different users.
Version 4.5.0

eg:
`Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E; GWX:RESERVED; rv:11.0) like Gecko`

**Comment by Pomax** [comment]
According to http://caniuse.com/#search=classList IE11 has support for the `classList` operations that this code relies on, so a reproducible test case will be necessary.

If you do happen to run into this such that it's reproducible, please file a new issue specifically for IE11 (this issue was about IE9)

**Comment by vguzev** [comment]
@Pomax We've created a clone of react-onclickoutside with IE9 support:
https://www.npmjs.com/package/react-onclickoutside-ie9
It would be great if someone could merge it into original project.

P.S. In countries like Russia or China some spheres (for example, corporate banking segment) have really high percentage of IE9 users. It's about 10%... So, we have to support IE9!

**Comment by Pomax** [comment]
Then you have big problems on the IE front, but practically speaking all you have to do is add the classlist shim to your page, like any other shim, and done. That is not something that needs to be handled by individual libraries you make use of, that's a global shim that *your page* simply loads before all other JS. You don't want to bloat each and every library you may need to use when the solution is a simple one-time global JS API shim.
