### ISSUE TITLE
Local node does not update if the inner component's root element changes

### ISSUE THREAD

**Issue by jshthornton** [Pomax/react-onclickoutside#66]
If the inner component on one render produces:
```
<div/>
```
The the next render produces
```
<form/>
```
The local node is not updated therefore the source not will never match.

**Comment by Pomax** [comment]
I'm not sure I understand; you should never do this, because that means your UI pretends that a form and a div are even remotely the same thing. Can you give an example of where this is happening, because I'm pretty sure you're working with highly improper UI code here, the solution to which would be to fix that code, not to change the behaviour of this mixin.

**Comment by jshthornton** [comment]
An example would be if you where working with a record / row, and the record is editable. When toggling it to edit it would become a form to change information. Granted they should be two different hot swapped components. Just pointing out a stale reference.

**Comment by Pomax** [comment]
That use case doesn't sound like a good example, why would the output of render change? The outer wrapper in render (`render() { return <div className...> ... </div>; }`) would still stay the same, even if its content changes.

**Comment by jshthornton** [comment]
I agree. It's not elegant. It's just an example of something that **can** happen, and stale references can cause more damage.

**Comment by Pomax** [comment]
Honestly, I'm okay with bad code leading to more badness. If a very weird UI code choice leads to stale references, I'm okay with this library not accommodating that and forcing code authors to fix the original problem instead.
