### ISSUE TITLE
Bring the mixin back.

### ISSUE THREAD

**Issue by sterpe** [Pomax/react-onclickoutside#85]
Obviously,  not everyone is using es6 class syntax with React, and I think as the README points out the discussion about how HOCs should work is not completely formalized.  I just feel like the mixin was a better approach than wrapping another component in `react-onclickoutside`.

**Comment by Pomax** [comment]
I don't have to, it's still right there. This is a *major* version upgrade, because everything changed. If you want, or need, the old 4.*, do so. Peg your version in your package.json, done:
```
  "dependencies": {
    ...
    "react-onclickoutside": "4.x",
    ...
  }
```
And voila. Mixin.

**Comment by sterpe** [comment]
No kidding.  But still feel a little unilateral.

**Comment by Pomax** [comment]
I hear that, and you're absolutely right in that it is, but as a developer I don't want to be maintaining code for versions of React that have all but been disavowed by the React team, so it is my responsibility to make sure that at some point, support for legacy code stops, and for react-onclickoutside that point last v5.

Having to move with the technology we chose to work with is a sometimes annoying consequence of the field we work (or play) in, and of all the ubiquitous projects I've seen so far, React moves *super fast*, they move through versions pretty rapidly, and older 0.12, 0.13 and 0.14 concepts, plugins and components have to keep up with those changes.

On the other hand I also want to make sure things that worked keep working, so I adhere to the semver standard, which `npm` honours; as long as new version doesn't break old versions, it's pushed as minor release, and when it --necessarily-- eventually does, it's a major version and `npm` will not update it for you unless you installed it manually with a version `*` or the like. So, for those who cannot immediately upgrade (because you don't always have that luxury), you get to keep using code that worked before without any changes, whereas people who come into React today will get a component that's intended to be used with the version of React they start on.

**Comment by sterpe** [comment]
Yeah, np.  I think the other thing with React/Jest/etc is that they actually push out into open source way ahead of what they actually are internally using, I've been trying to stay back a bit of the bleeding edge on some of this.

I don't want to make it sound like I think you owe OSS community something, not my point, at all, just that I don't know how widespread ES6 Classes are being used in React applications generally, because mixins are so powerful, and with Classes they are totally unavailable, I suspect they are less in use than you I think.  Fair enough, you have to write code to support your own use case first.

I got nailed on Semver because I did fresh install manually, and was like what?!  ;)

**Comment by sterpe** [comment]
Personal project, I _might_ play with ES6 classes and React, but not for any type of professional application.

**Comment by Pomax** [comment]
The nice thing about ES6 is that uptake's getting pretty good. Node 4 has it waiting for you to enable it with the `--harmony` flag when you run node, and Node 5 simply runs in ES6 mode (which as a superset of ES5 means you usually don't even notice it has full ES6 support), and Firefox and Chrome already support pretty much everything in ES6 that is worth using today (IE is still working on landing most of ES6 in their IE Edge, so we're not quite at universal uptake yet).

I've held off moving to React 15 for a while, but it's been almost a month and a half and I'm only hearing good things about it, so it's time to make the switch. Not sure I'll use full ES6 classes quite yet, but even the basic ES6 syntax makes life a lot easier.

This is super nice, for instance:
```
var MyComponent = React.createClass({
  render() {
    return this.state.elements.map(e => <CustomThing {...e} onClick={this.handleClick} />);
  }
});
```

**Comment by sterpe** [comment]
This is actually what we're doing.  ES6 syntax, but not React classes.  So
we still use `React.createClass()` and still get to use mixins, but for the
actual js syntax we are doing ES6 then via Babel to ES5.

We are also still running React 0.14.  After a while, we just got tired of
chasing these guys every couple of months.

**Comment by Pomax** [comment]
It feels like with React, you're kind of stuck with "5 months of pretty awesome new stuff" and then a few weeks of porting to the new version. It can certainly get tiring! =)

And hopefully the next few releases of React can bring some clarity to the "official" way to do HOCs, too.
