### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gusdaud** [Pomax/react-onclickoutside#93]
I see by the packages.json that the license is MIT.
 
Could you include the license file in the new releases ?

**Comment by Pomax** [comment]
Can you explain why you feel this is necessary? It's already clear what the license is, having the actual MIT text in a text file in the dir seems pretty pointless.

**Comment by gusdaud** [comment]
Hi Pomax, we developers know that we should be looking for the license type in the packages.json entry but it may not be so clear for others whom doesn't have the technical skill. Also it is very common for GIT projects to have a LICENSE.md file in the project root folder.

**Comment by Pomax** [comment]
Hm, neither of these seem particularly compelling reasons to add the license as separate file, though.

While it might be true that non-developers may not know where to look for the license information for projects on Github, Github is not where people are going to initially find this package. They're almost certainly going find it through https://www.npmjs.com/package/react-onclickoutside instead, which means they'll already be clearly confronted with package license information (it's on the right of the page). No need for them to ever be on Github for that, *unless* they are a developer. So that's not enough reason (for me, at least) to add a license file that's just going to download itself to people's disks without ever being read by them, or being deduplicated because it's already on that same disk a million times, or in fact having any kind of meaningful contribution to the codebase.

Similarly, just because something's common practice doesn't mean it's required practice, or even sensible practice. Why waste bytes on a file that is just going to take up space, and for which a canonical form can be trivially found with a web search?

Unless there is literally a legal requirement for that file to take up bytes on the repository, I'll quite happily leave it off.

**Comment by gusdaud** [comment]
Ok Pomax. I understand your point of view.

Anyway, thanks for the component, it has being helpful.
