### ISSUE TITLE
Does not work if on initial render component returns null

### ISSUE THREAD

**Issue by nvartolomei** [Pomax/react-onclickoutside#96]
Didn't have much time to dig this, but if component wrapped with onClickOutside returns null on initial render, and later renders some content, click to new content will be considered outside.

I understand why this happens, but at least let's add a warning when someones renders empty element inside wrapped component.

**Comment by Pomax** [comment]
that doesn't make sense. Your render should not be yielding `null`, the parent should be deciding whether or not to render the component instead.

**Comment by nvartolomei** [comment]
@Pomax let's consider it a smart component that that I didn't want to wrap into a dumb component which then would be wrapped in onclickoutside. I didn't say this is right, but react-onclickoutside could check if component node is a valid one and show an error/warning.

Or maybe add a warning to readme :)

**Comment by nvartolomei** [comment]
Quick question: What will happen if I render if my component renders a div on mount and then later it rerenders something else? 🤔

**Comment by Pomax** [comment]
hopefully, "the same thing", as it's supposed to use the components run-time DOM node that comes rolling out of a `ReactDOM.findDOMNode(yourcomponent)`. If that is not the case, we probably have a bug. 

However, if the render returns a `null`, there is no DOM element to test in/outsidedness on, and then that would be a flaw in the design of whatever code's trying to use this library. 

It sounds like we need to (1) make sure `findDOMNode` is used as late as possible, and (2) shortcircuit when there is *no* DOM node associated because someone was silly enough to make render output `null`. Does that sound like a fair assessment?

**Comment by nvartolomei** [comment]
If render method looks like this:
```js
// fake code
render() {
  if (this.state.isFetching) {
    return <Spinner />;
  }

  return <Data {...this.state} />;
}
```

In this case clicks inside **Data** will be considered outside because outsideCheck is generated for **Spinner** component.

First solution, how late? On each mousedown/touchstart?
What short-circuiting means in this case?
Wrapping wrapped component into another div and use it as instance may work too, though didn't test and will add a ugly div that can break someone else's code.

So far the best solution looks like is adding a note about this to README :)

**Comment by Pomax** [comment]
first solution: on each attempt, because if we have to take into account that an element by render null, there will not *be* a DOM element to chain-check, and we won't know until we check at request-time.

short-circuit: detect if element is null. If so, immediately return whatever is necessary for code to do the right thing instead of still running through the "is this node in the chain" check.

if you have a suggestion for the README.md extension, please hit up https://github.com/Pomax/react-onclickoutside/edit/master/README.md, click the "edit" button, put your text where you think it'll do the most good, and then click the big button that turns your edit into a commit and lets you file a PR all just using github, without ever having had to clone the project to your computer, etc. (very handy)

**Comment by Pomax** [comment]
closing to prevent the issue from going stale.
